### ISSUE TITLE
Unable to find image 'mapping_ipp_framework_mapping_ipp:latest' locally

### ISSUE THREAD

**Issue by LLL-YUE** [dmar-bonn/ipp-rl#3]
![屏幕截图 2024-04-12 120126](https://github.com/dmar-bonn/ipp-rl/assets/95279388/9501f5ca-1920-4eb2-8442-d81ad94e1e54)
When I run ./build.sh，I got the error as follows. How can I solve this problem?

**Comment by smoggy-P** [comment]
Hi, I got the same problem. How did you solve it?
